# Data Visualization with Modern Data Science

> Final

Yao-Jen Kuo <yaojenkuo@ntu.edu.tw> from [DATAINPOINT](https://www.datainpoint.com)

In [ ]:
import unittest
import requests
import numpy as np
import pandas as pd

## Instructions

- Write down your solution between comments `### BEGIN SOLUTION` and `### END SOLUTION`.
- Running tests to see if your solutions are right:
    - Runtime -> Restart and run all.
- When you are ready to submit, click File -> Download -> Download `.py`.

![](https://i.imgur.com/Y1BcDdx.png)

- Open a new Colab in a private window, upload the script and run tests again before submission to make sure the script is executable in a fresh new Colab.

![](https://i.imgur.com/ojlvbds.png)

- Upload to the Assignment session on NTU COOL.

In [ ]:
file_names = ["time_series_covid19_confirmed_global.csv", "time_series_covid19_deaths_global.csv", 
              "players.csv", "season_average.csv", "teams.csv"]
for file_name in file_names:
    file_url = f"https://raw.githubusercontent.com/datainpoint/asgmts-data-viz-with-modern-ds-2023/main/{file_name}"
    r = requests.get(file_url)
    with open(file_name , 'wb') as f:
        f.write(r.content)

## 01. Define a function `import_time_series_confirmed_deaths()` which imports `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` in working directory.

In [ ]:
def import_time_series_confirmed_deaths() -> tuple:
    """
    >>> time_series_confirmed, time_series_deaths = import_time_series_confirmed_deaths()
    >>> type(time_series_confirmed)
    pandas.core.frame.DataFrame
    >>> type(time_series_deaths)
    pandas.core.frame.DataFrame
    >>> time_series_confirmed.shape
    (289, 1147)
    >>> time_series_deaths.shape
    (289, 1147)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 02. Define a function `transform_time_series_confirmed_deaths()` which transforms both `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` from wide format into long format.

In [ ]:
def transform_time_series_confirmed_deaths() -> tuple:
    """
    >>> time_series_confirmed_long, time_series_deaths_long = transform_time_series_confirmed_deaths()
    >>> type(time_series_confirmed_long)
    pandas.core.frame.DataFrame
    >>> type(time_series_deaths_long)
    pandas.core.frame.DataFrame
    >>> time_series_confirmed_long.shape
    (330327, 6)
    >>> time_series_deaths_long.shape
    (330327, 6)
    >>> print(time_series_confirmed_long)
           Province/State        Country/Region        Lat        Long     Date  \
    0                 NaN           Afghanistan  33.939110   67.709953  1/22/20   
    1                 NaN               Albania  41.153300   20.168300  1/22/20   
    2                 NaN               Algeria  28.033900    1.659600  1/22/20   
    3                 NaN               Andorra  42.506300    1.521800  1/22/20   
    4                 NaN                Angola -11.202700   17.873900  1/22/20   
    ...               ...                   ...        ...         ...      ...   
    330322            NaN    West Bank and Gaza  31.952200   35.233200   3/9/23   
    330323            NaN  Winter Olympics 2022  39.904200  116.407400   3/9/23   
    330324            NaN                 Yemen  15.552727   48.516388   3/9/23   
    330325            NaN                Zambia -13.133897   27.849332   3/9/23   
    330326            NaN              Zimbabwe -19.015438   29.154857   3/9/23   

            Confirmed  
    0               0  
    1               0  
    2               0  
    3               0  
    4               0  
    ...           ...  
    330322     703228  
    330323        535  
    330324      11945  
    330325     343135  
    330326     264276  

    [330327 rows x 6 columns]
    >>> print(time_series_deaths_long)
           Province/State        Country/Region        Lat        Long     Date  \
    0                 NaN           Afghanistan  33.939110   67.709953  1/22/20   
    1                 NaN               Albania  41.153300   20.168300  1/22/20   
    2                 NaN               Algeria  28.033900    1.659600  1/22/20   
    3                 NaN               Andorra  42.506300    1.521800  1/22/20   
    4                 NaN                Angola -11.202700   17.873900  1/22/20   
    ...               ...                   ...        ...         ...      ...   
    330322            NaN    West Bank and Gaza  31.952200   35.233200   3/9/23   
    330323            NaN  Winter Olympics 2022  39.904200  116.407400   3/9/23   
    330324            NaN                 Yemen  15.552727   48.516388   3/9/23   
    330325            NaN                Zambia -13.133897   27.849332   3/9/23   
    330326            NaN              Zimbabwe -19.015438   29.154857   3/9/23   

            Deaths  
    0            0  
    1            0  
    2            0  
    3            0  
    4            0  
    ...        ...  
    330322    5708  
    330323       0  
    330324    2159  
    330325    4057  
    330326    5671  

    [330327 rows x 6 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 03. Define a function `merge_time_series_confirmed_deaths()` which merges the long formatted `time_series_covid19_confirmed_global.csv` and `time_series_covid19_deaths_global.csv` into one data frame.

In [ ]:
def merge_time_series_confirmed_deaths() -> pd.core.frame.DataFrame:
    """
    >>> merged_time_series = merge_time_series_confirmed_deaths()
    >>> type(merged_time_series)
    pd.core.frame.DataFrame
    >>> merged_time_series.shape
    (330327, 7)
    >>> print(merged_time_series)
               Date Province/State        Country/Region        Lat        Long  \
    0       1/22/20            NaN           Afghanistan  33.939110   67.709953   
    1       1/22/20            NaN               Albania  41.153300   20.168300   
    2       1/22/20            NaN               Algeria  28.033900    1.659600   
    3       1/22/20            NaN               Andorra  42.506300    1.521800   
    4       1/22/20            NaN                Angola -11.202700   17.873900   
    ...         ...            ...                   ...        ...         ...   
    330322   3/9/23            NaN    West Bank and Gaza  31.952200   35.233200   
    330323   3/9/23            NaN  Winter Olympics 2022  39.904200  116.407400   
    330324   3/9/23            NaN                 Yemen  15.552727   48.516388   
    330325   3/9/23            NaN                Zambia -13.133897   27.849332   
    330326   3/9/23            NaN              Zimbabwe -19.015438   29.154857   

            Confirmed  Deaths  
    0               0       0  
    1               0       0  
    2               0       0  
    3               0       0  
    4               0       0  
    ...           ...     ...  
    330322     703228    5708  
    330323        535       0  
    330324      11945    2159  
    330325     343135    4057  
    330326     264276    5671  

    [330327 rows x 7 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 04. Define a function `summarize_latest_daily_report()` which summarizes the total confirmed and deaths by country as of 2023-03-09.

In [ ]:
def summarize_latest_daily_report() -> pd.core.frame.DataFrame:
    """
    >>> latest_daily_report = summarize_latest_daily_report()
    >>> type(latest_daily_report)
    pandas.core.frame.DataFrame
    >>> latest_daily_report.shape
    (201, 3)
    >>> print(latest_daily_report)
               Country/Region  Confirmed  Deaths
    0             Afghanistan     209451    7896
    1                 Albania     334457    3598
    2                 Algeria     271496    6881
    3                 Andorra      47890     165
    4                  Angola     105288    1933
    ..                    ...        ...     ...
    196    West Bank and Gaza     703228    5708
    197  Winter Olympics 2022        535       0
    198                 Yemen      11945    2159
    199                Zambia     343135    4057
    200              Zimbabwe     264276    5671

    [201 rows x 3 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 05. Define a function `filter_taiwan_time_series()` which filters the data of `'Taiwan*'` and format `Date` with ISO-8601 format `yyyy-mm-dd`(`%Y-%m-%d`).

In [ ]:
def filter_taiwan_time_series() -> pd.core.frame.DataFrame:
    """
    >>> taiwan_time_series = filter_taiwan_time_series()
    >>> type(taiwan_time_series)
    pandas.core.frame.DataFrame
    >>> taiwan_time_series.shape
    (1143, 7)
    >>> print(taiwan_time_series)
               Date Province/State Country/Region   Lat   Long  Confirmed  Deaths
    0    2020-01-22            NaN        Taiwan*  23.7  121.0          1       0
    1    2020-01-23            NaN        Taiwan*  23.7  121.0          1       0
    2    2020-01-24            NaN        Taiwan*  23.7  121.0          3       0
    3    2020-01-25            NaN        Taiwan*  23.7  121.0          3       0
    4    2020-01-26            NaN        Taiwan*  23.7  121.0          4       0
    ...         ...            ...            ...   ...    ...        ...     ...
    1138 2023-03-05            NaN        Taiwan*  23.7  121.0    9970937   17672
    1139 2023-03-06            NaN        Taiwan*  23.7  121.0    9970937   17672
    1140 2023-03-07            NaN        Taiwan*  23.7  121.0    9970937   17672
    1141 2023-03-08            NaN        Taiwan*  23.7  121.0    9970937   17672
    1142 2023-03-09            NaN        Taiwan*  23.7  121.0    9970937   17672

    [1143 rows x 7 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 06. Define a function named `calculate_twn_daily_confirmed_deaths()` which calculates the column `daily_confirmed` and `daily_deaths` from the output of `filter_taiwan_time_series()`.

\begin{equation}
\text{daily}[i] = \text{cumulative}[i+1] - \text{cumulative}[i]
\end{equation}

In [ ]:
def calculate_twn_daily_confirmed_deaths() -> pd.core.frame.DataFrame:
    """
    >>> twn_daily_confirmed_deaths = calculate_twn_daily_confirmed_deaths()
    >>> type(twn_daily_confirmed_deaths)
    pandas.core.frame.DataFrame
    >>> twn_daily_confirmed_deaths.shape
    (1143, 9)
    >>> print(twn_daily_confirmed_deaths)
               Date Province/State Country/Region   Lat   Long  Confirmed  Deaths  \
    0    2020-01-22            NaN        Taiwan*  23.7  121.0          1       0   
    1    2020-01-23            NaN        Taiwan*  23.7  121.0          1       0   
    2    2020-01-24            NaN        Taiwan*  23.7  121.0          3       0   
    3    2020-01-25            NaN        Taiwan*  23.7  121.0          3       0   
    4    2020-01-26            NaN        Taiwan*  23.7  121.0          4       0   
    ...         ...            ...            ...   ...    ...        ...     ...   
    1138 2023-03-05            NaN        Taiwan*  23.7  121.0    9970937   17672   
    1139 2023-03-06            NaN        Taiwan*  23.7  121.0    9970937   17672   
    1140 2023-03-07            NaN        Taiwan*  23.7  121.0    9970937   17672   
    1141 2023-03-08            NaN        Taiwan*  23.7  121.0    9970937   17672   
    1142 2023-03-09            NaN        Taiwan*  23.7  121.0    9970937   17672   

          daily_confirmed  daily_deaths  
    0                 NaN           NaN  
    1                 0.0           0.0  
    2                 2.0           0.0  
    3                 0.0           0.0  
    4                 1.0           0.0  
    ...               ...           ...  
    1138              0.0           0.0  
    1139              0.0           0.0  
    1140              0.0           0.0  
    1141              0.0           0.0  
    1142              0.0           0.0  

    [1143 rows x 9 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 07. Define a function named `import_nba_csvs()` which imports the files `teams.csv`, `players.csv`, and `season_average.csv` in working directory.

In [ ]:
def import_nba_csvs() -> tuple:
    """
    >>> players, season_average, teams = import_nba_csvs()
    >>> type(players)
    pandas.core.frame.DataFrame
    >>> type(season_average)
    pandas.core.frame.DataFrame
    >>> type(teams)
    pandas.core.frame.DataFrame
    >>> players.shape
    (539, 8)
    >>> season_average.shape
    (539, 23)
    >>> teams.shape
    (30, 7)
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 08. Define a function named `filter_teams_of_the_nba_playoffs_2023()` which filters the teams of 2023 playoff given `teams.csv` in working directory.

```python
playoff_teams = ["Bucks", "Heat", "Cavaliers", "Knicks", "76ers", "Nets", "Celtics", "Hawks", "Nuggets", "Timberwolves", "Suns", "Clippers", "Kings", "Warriors", "Grizzlies", "Lakers"]
```

In [ ]:
def filter_teams_of_the_nba_playoffs_2023() -> pd.core.frame.DataFrame:
    """
    >>> teams_of_the_nba_playoffs_2023 = filter_teams_of_the_nba_playoffs_2023()
    >>> type(teams_of_the_nba_playoffs_2023)
    pandas.core.frame.DataFrame
    >>> teams_of_the_nba_playoffs_2023.shape
    (16, 7)
    >>> print(teams_of_the_nba_playoffs_2023)
        id abbreviation          city conference   division  \
    0    1          ATL       Atlanta       East  Southeast   
    1    2          BOS        Boston       East   Atlantic   
    2    3          BKN      Brooklyn       East   Atlantic   
    5    6          CLE     Cleveland       East    Central   
    7    8          DEN        Denver       West  Northwest   
    9   10          GSW  Golden State       West    Pacific   
    12  13          LAC            LA       West    Pacific   
    13  14          LAL   Los Angeles       West    Pacific   
    14  15          MEM       Memphis       West  Southwest   
    15  16          MIA         Miami       East  Southeast   
    16  17          MIL     Milwaukee       East    Central   
    17  18          MIN     Minnesota       West  Northwest   
    19  20          NYK      New York       East   Atlantic   
    22  23          PHI  Philadelphia       East   Atlantic   
    23  24          PHX       Phoenix       West    Pacific   
    25  26          SAC    Sacramento       West    Pacific   

                     full_name          name  
    0            Atlanta Hawks         Hawks  
    1           Boston Celtics       Celtics  
    2            Brooklyn Nets          Nets  
    5      Cleveland Cavaliers     Cavaliers  
    7           Denver Nuggets       Nuggets  
    9    Golden State Warriors      Warriors  
    12             LA Clippers      Clippers  
    13      Los Angeles Lakers        Lakers  
    14       Memphis Grizzlies     Grizzlies  
    15              Miami Heat          Heat  
    16         Milwaukee Bucks         Bucks  
    17  Minnesota Timberwolves  Timberwolves  
    19         New York Knicks        Knicks  
    22      Philadelphia 76ers         76ers  
    23            Phoenix Suns          Suns  
    25        Sacramento Kings         Kings
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 09. Define a function `list_roster_of_the_nba_playoffs_2023()` which lists the roster of all 2023 playoff teams given `teams.csv` and `players.csv`.

```python
playoff_teams = ["Bucks", "Heat", "Cavaliers", "Knicks", "76ers", "Nets", "Celtics", "Hawks", "Nuggets", "Timberwolves", "Suns", "Clippers", "Kings", "Warriors", "Grizzlies", "Lakers"]
```

In [ ]:
def list_roster_of_the_nba_playoffs_2023() -> pd.core.frame.DataFrame:
    """
    >>> roster_of_the_nba_playoffs_2023 = list_roster_of_the_nba_playoffs_2023()
    >>> type(roster_of_the_nba_playoffs_2023)
    pandas.core.frame.DataFramez
    >>> roster_of_the_nba_playoffs_2023.shape
    (282, 4)
    >>> print(roster_of_the_nba_playoffs_2023)
        conference abbreviation first_name   last_name
    0         East          ATL         AJ     Griffin
    1         East          ATL      Aaron     Holiday
    2         East          ATL     Bogdan  Bogdanovic
    3         East          ATL      Bruno    Fernando
    4         East          ATL      Clint      Capela
    ..         ...          ...        ...         ...
    277       West          SAC    Neemias       Queta
    278       West          SAC         PJ      Dozier
    279       West          SAC    Richaun      Holmes
    280       West          SAC    Terence       Davis
    281       West          SAC       Trey       Lyles

    [282 rows x 4 columns]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 10. Define a function `list_roster_of_the_nba_finals_2023()` which lists the roster of the NBA Finals 2023, the Miami Heat and the Denver Nuggets. Sort players with their points given `teams.csv`, `players.csv`, and `season_average.csv` in working directory.

In [ ]:
def list_roster_of_the_nba_finals_2023() -> pd.core.frame.DataFrame:
    """
    >>> roster_of_the_nba_finals_2023 = list_roster_of_the_nba_finals_2023()
    >>> type(roster_of_the_nba_finals_2023)
    pandas.core.frame.DataFrame
    >>> roster_of_the_nba_finals_2023.shape
    (33, 5)
    >>> print(roster_of_the_nba_finals_2023)
       conference abbreviation  first_name      last_name    pts
    0        East          MIA       Jimmy         Butler  23.00
    1        East          MIA         Bam        Adebayo  20.12
    2        East          MIA       Tyler          Herro  20.07
    3        East          MIA         Max          Strus  11.67
    4        East          MIA        Kyle          Lowry  11.46
    5        East          MIA      Victor        Oladipo  10.44
    6        East          MIA       Caleb         Martin   9.44
    7        East          MIA        Gabe        Vincent   9.24
    8        East          MIA       Kevin           Love   8.13
    9        East          MIA      Duncan       Robinson   6.38
    10       East          MIA        Cody         Zeller   6.25
    11       East          MIA      Nikola          Jovic   5.47
    12       East          MIA       Jamal           Cain   5.44
    13       East          MIA        Omer      Yurtseven   4.44
    14       East          MIA     Haywood      Highsmith   4.37
    15       East          MIA      Udonis         Haslem   3.86
    16       East          MIA     Orlando       Robinson   3.74
    17       West          DEN      Nikola          Jokic  24.49
    18       West          DEN       Jamal         Murray  19.97
    19       West          DEN     Michael     Porter Jr.  17.42
    20       West          DEN       Aaron         Gordon  16.31
    21       West          DEN       Bruce          Brown  11.54
    22       West          DEN  Kentavious  Caldwell-Pope  10.82
    23       West          DEN      Reggie        Jackson  10.19
    24       West          DEN      Thomas         Bryant   9.81
    25       West          DEN        Jeff          Green   7.80
    26       West          DEN        Zeke          Nnaji   5.23
    27       West          DEN     DeAndre         Jordan   5.10
    28       West          DEN      Vlatko         Cancar   4.95
    29       West          DEN   Christian          Braun   4.74
    30       West          DEN      Peyton         Watson   3.26
    31       West          DEN         Ish          Smith   2.51
    32       West          DEN        Jack          White   1.24
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## End of assignment, ignore the following cells.

In [ ]:
class TestFinal(unittest.TestCase):
    def test_01_import_time_series_confirmed_deaths(self):
        time_series_confirmed, time_series_deaths = import_time_series_confirmed_deaths()
        self.assertIsInstance(time_series_confirmed, pd.core.frame.DataFrame)
        self.assertIsInstance(time_series_deaths, pd.core.frame.DataFrame)
        self.assertEqual(time_series_confirmed.shape, (289, 1147))
        self.assertEqual(time_series_deaths.shape, (289, 1147))
    def test_02_transform_time_series_confirmed_deaths(self):
        time_series_confirmed_long, time_series_deaths_long = transform_time_series_confirmed_deaths()
        self.assertIsInstance(time_series_confirmed_long, pd.core.frame.DataFrame)
        self.assertIsInstance(time_series_deaths_long, pd.core.frame.DataFrame)
        self.assertEqual(time_series_confirmed_long.shape, (330327, 6))
        self.assertEqual(time_series_deaths_long.shape, (330327, 6))
    def test_03_merge_time_series_confirmed_deaths(self):
        merged_time_series = merge_time_series_confirmed_deaths()
        self.assertIsInstance(merged_time_series, pd.core.frame.DataFrame)
        self.assertEqual(merged_time_series.shape, (330327, 7))
    def test_04_summarize_latest_daily_report(self):
        latest_daily_report = summarize_latest_daily_report()
        self.assertIsInstance(latest_daily_report, pd.core.frame.DataFrame)
        self.assertEqual(latest_daily_report.shape, (201, 3))
    def test_05_filter_taiwan_time_series(self):
        taiwan_time_series = filter_taiwan_time_series()
        self.assertIsInstance(taiwan_time_series, pd.core.frame.DataFrame)
        self.assertEqual(taiwan_time_series.shape, (1143, 7))
    def test_06_calculate_twn_daily_confirmed_deaths(self):
        twn_daily_confirmed_deaths = calculate_twn_daily_confirmed_deaths()
        self.assertIsInstance(twn_daily_confirmed_deaths, pd.core.frame.DataFrame)
        self.assertEqual(twn_daily_confirmed_deaths.shape, (1143, 9))
    def test_07_import_nba_csvs(self):
        players, season_average, teams = import_nba_csvs()
        self.assertIsInstance(players, pd.core.frame.DataFrame)
        self.assertIsInstance(season_average, pd.core.frame.DataFrame)
        self.assertIsInstance(teams, pd.core.frame.DataFrame)
        self.assertEqual(players.shape, (539, 8))
        self.assertEqual(season_average.shape, (539, 23))
        self.assertEqual(teams.shape, (30, 7))
    def test_08_filter_teams_of_the_nba_playoffs_2023(self):
        teams_of_the_nba_playoffs_2023 = filter_teams_of_the_nba_playoffs_2023()
        self.assertIsInstance(teams_of_the_nba_playoffs_2023, pd.core.frame.DataFrame)
        self.assertEqual(teams_of_the_nba_playoffs_2023.shape, (16, 7))
        self.assertEqual(teams_of_the_nba_playoffs_2023.iloc[:, 3].nunique(), 2)
        self.assertEqual(teams_of_the_nba_playoffs_2023.iloc[:, 1].nunique(), 16)
        self.assertIn("DEN", teams_of_the_nba_playoffs_2023["abbreviation"].values)
        self.assertIn("LAL", teams_of_the_nba_playoffs_2023["abbreviation"].values)
        self.assertIn("MIA", teams_of_the_nba_playoffs_2023["abbreviation"].values)
        self.assertIn("BOS", teams_of_the_nba_playoffs_2023["abbreviation"].values)
    def test_09_list_roster_of_the_nba_playoffs_2023(self):
        roster_of_the_nba_playoffs_2023 = list_roster_of_the_nba_playoffs_2023()
        self.assertIsInstance(roster_of_the_nba_playoffs_2023, pd.core.frame.DataFrame)
        self.assertEqual(roster_of_the_nba_playoffs_2023.shape, (282, 4))
        self.assertEqual(roster_of_the_nba_playoffs_2023.iloc[:, 0].nunique(), 2)
    def test_10_list_roster_of_the_nba_finals_2022(self):
        roster_of_the_nba_finals_2023 = list_roster_of_the_nba_finals_2023()
        self.assertIsInstance(roster_of_the_nba_finals_2023, pd.core.frame.DataFrame)
        self.assertEqual(roster_of_the_nba_finals_2023.shape, (33, 5))      
        self.assertEqual(roster_of_the_nba_finals_2023.iloc[:, 0].nunique(), 2)
        self.assertEqual(roster_of_the_nba_finals_2023.iloc[:, 1].nunique(), 2)
        first_names = ["Jimmy", "Bam", "Caleb", "Nikola", "Jamal", "Aaron"]
        for first_name in first_names:
            self.assertIn(first_name, roster_of_the_nba_finals_2023.iloc[:, 2].values)
        
suite = unittest.TestLoader().loadTestsFromTestCase(TestFinal)
runner = unittest.TextTestRunner(verbosity=2)
test_results = runner.run(suite)
number_of_failures = len(test_results.failures)
number_of_errors = len(test_results.errors)
number_of_test_runs = test_results.testsRun
number_of_successes = number_of_test_runs - (number_of_failures + number_of_errors)

In [ ]:
print("You've got {} successes among {} questions.".format(number_of_successes, number_of_test_runs))